server:
#  servlet:
  context-path: /joinmeds-service
  port: 8085
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://69.62.73.165:5432/join_meds
    username: yourusername
    password: 123ikm

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
file:
  upload-dir: uploads/photos
  resume-dir: uploads/resumes
